export const SET_DARK_MODE = "SET_DARK_MODE"
export const SET_DEPARTURE = "SET_DEPARTURE";
export const SET_ARRIVALS = "SET_ARRIVALS";
export const SET_NUMBER_OF_PASSENGER = "SET_NUMBER_OF_PASSENGER";
export const SET_SELECTED_FLIGHT = "SET_SELECTED_FLIGHT";
export const SET_QUERY_RESULTS = "SET_QUERY_RESULTS";
export const SET_PROMOTION_TOGGLE = "SET_PROMOTION_TOGGLE";
export const SET_SORT_TYPE = "SET_SORT_TYPE";
